### ISSUE TITLE
Homework Feedback

### ISSUE THREAD

**Issue by arun-instructor** [WhitC/responsivefashionblog#2]
Whit,

This is coming along well. I think you have the right idea and are making progress. Be careful how you work with your columns. For example, you have this:

```css
.col-2 {
    width:100%;
    max-width: 500px;
    padding: 20px;
    text-align: center;
    background: black;
    color: white;
}
```

This is making the col-2 100% width even under normal browser widths. This is causing the stacking when at desktop resolutions.
